# Generated by Django 3.1.3 on 2020-12-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('github', models.URLField()),
                ('demo', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
